"""Initial migration

Revision ID: 8e61b67dfee3
Revises: 
Create Date: 2026-07-13 11:42:25.833490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e61b67dfee3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_google_id'), 'admin_users', ['google_id'], unique=True)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=False),
    sa.Column('from_location', sa.String(), nullable=False),
    sa.Column('to_location', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('qr_code_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('latest_executive', sa.String(), nullable=True),
    sa.Column('latest_scan_location', sa.String(), nullable=True),
    sa.Column('latest_scan_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_tracking_id'), 'shipments', ['tracking_id'], unique=True)
    op.create_table('handling_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('executive_name', sa.String(), nullable=False),
    sa.Column('package_photo_url', sa.String(), nullable=False),
    sa.Column('selfie_photo_url', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handling_events')
    op.drop_index(op.f('ix_shipments_tracking_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_google_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
